### ISSUE TITLE
Custom county simulation?

### ISSUE THREAD

**Issue by bbennett80** [youyanggu/yyg-seir-simulator#1]
What are the parameters to create a custom county simulation file?  I'm in Kern County, Ca.

**Comment by youyanggu** [comment]
Since we don't have projections for Kern County, CA, we don't have the parameters.

You'd have to effectively do trial and error yourself and try different parameters such that the resulting outputs match the actual data from Kern County, or any other county you want to have simulations for.

**Comment by bbennett80** [comment]
Ok cool. Thank you for the direction. I'll run some trials (with mostly errors I'm sure) this weekend.
