### ISSUE TITLE
Benchmarking with Seroprevalence data

### ISSUE THREAD

**Issue by rexdouglass** [youyanggu/yyg-seir-simulator#2]
As I understand it, this model backs out cases from deaths using a strong prior on the IFR (https://twitter.com/youyanggu/status/1286421304401375234).

Is that correct, and if so have you considered using the new round of seroprevalance estimates we're getting, e.g. 10 locations for end of March/start of May (https://jamanetwork.com/journals/jamainternalmedicine/fullarticle/2768834).

Accertainment looks like it might be improving, moving from 1 in 10 to close to 1 in 5ish as testing ramps up (https://twitter.com/trvrb/status/1286092969875914752).

IFR assumptions are really a rough way to go, ideally we would weaken our prior over that and start to lean on other measurements jointly.

**Comment by youyanggu** [comment]
Thanks for your note. Yes, back in April/May we were benchmarking our IFR based on serological studies, especially large-scale ones carried out in New York.

One note of caution regarding the recent study you referenced is the following quote:

> This cross-sectional study performed serologic testing on a convenience sample of residual sera obtained from persons of all ages.

It is not a randomized sample, and hence can be subject to a wide variety of biases (e.g. people who go to clinics to have their blood drawn may be more likely to be sick/have been sick in the past). So while the data is useful, I would take the results they present with a grain of salt.

**Comment by redknightlois** [comment]
Probably would be of use. This one is randomized with very high seroprevalence under probably the worst living conditions (multi-family households). 
https://www.medrxiv.org/content/10.1101/2020.07.14.20153858v1.full.pdf 
IFR = 0.16

**Comment by rexdouglass** [comment]
Agreed. I'm trying to think through if we could at least sign the bias, of those by age group who are getting non-covid testing done, do we think they have higher or lower COVID-19 rates than the general public. Purely speculation but probably wealthier, whiter, more high risk, and more health conscious implies a lower rate than the average population.

Two random ones from about the same time period in the U.S:
Two counties in Atlanta
https://www.cdc.gov/mmwr/volumes/69/wr/mm6929e2.htm

Indiana
https://www.cdc.gov/mmwr/volumes/69/wr/mm6929e1.htm
