### ISSUE TITLE
NameError: name 'NO_LOCKDOWN_COUNTRIES' is not defined

### ISSUE THREAD

**Issue by berntisak** [youyanggu/yyg-seir-simulator#3]
The commit 87efc76a5e3e271e669212dcf4cc3b4a6707cad2 (1st of September) which adds `and self.country_str not in NO_LOCKDOWN_COUNTRIES:` on line 144 of region_model.py produces this error when trying to run a simulation:

>   yyg-seir-simulator/region_model.py", line 144, in get_reopen_r
>     if self.LOCKDOWN_R_0 < 1 and self.country_str not in NO_LOCKDOWN_COUNTRIES:
> NameError: name 'NO_LOCKDOWN_COUNTRIES' is not defined

Im running with these arguments: python run_simulation.py -v --best_params_dir best_params/latest --country "Germany" --simulation_end_date 2020-10-12

Commit 0dc19fbe70f11783ae25d9d3a1902ff4f257a951 from 31st of August works fine.

**Comment by youyanggu** [comment]
Thank you for bringing this to my attention. I made a commit that addresses this issue: https://github.com/youyanggu/yyg-seir-simulator/commit/9c9245d3db6d9d1855b7df9322cef2718cb4bb39

I did a force push so you may need to re-update your local version. Apologies for that.

**Comment by berntisak** [comment]
Thanks! Works again now
